# Starship configuration - Contextual and practical prompt
# Shows relevant info based on current directory context
# Organized alphabetically for easy maintenance

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$shell\
$sudo\
$username\
$hostname\
$package\
$nodejs\
$python\
$ruby\
$java\
$bun\
$docker_context\
$kubernetes\
$aws\
$gcloud\
$direnv\
$status\
$cmd_duration\
$jobs\
$line_break\
$character"""

# AWS - disabled by default, only enable in AWS projects
[aws]
disabled = true
symbol = " "
format = 'on [$symbol($profile )]($style)'

[buf]
symbol = " "

[bun]
symbol = " "
format = "via [$symbol$version]($style) "
detect_files = ["bun.lockb", "bunfig.toml"]

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

# Directory - show more context with better styling
[directory]
truncation_length = 4
truncation_symbol = "…/"
home_symbol = "~"
style = "bold cyan"
read_only = " 🔒"
read_only_style = "red"

# Docker - only show when in Docker context
[docker_context]
disabled = true
symbol = " "
format = "via [$symbol$context]($style) "
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
disabled = true
symbol = " "
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '

# Git - clean and informative with better styling
[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "bold purple"

[git_commit]
tag_symbol = ' '
commit_hash_length = 7
format = "([\\($hash$tag\\)]($style) )"
style = "green bold"
only_detached = true

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold red"
conflicted = "⚡"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = "✓"
untracked = "?"
stashed = "📦"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "
disabled = false
ssh_only = true
format = "[$hostname]($style) "

[java]
symbol = " "
format = "via [$symbol$version]($style) "
detect_files = ["pom.xml", "build.gradle", ".java-version"]

# Background jobs (like P10k's background_jobs)
[jobs]
format = "[$symbol$number]($style) "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
disabled = false
format = 'on [$symbol$context( \($namespace\))]($style) '
# Only show in directories with k8s files
detect_files = ["k8s", "kustomization.yaml", "Chart.yaml"]
detect_folders = ["k8s", "kubernetes", ".kube"]

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = "via [$symbol$version]($style) "
detect_files = ["package.json", ".nvmrc", "yarn.lock", "pnpm-lock.yaml"]
detect_folders = ["node_modules"]

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = " "
Illumos = " "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = " "

[package]
symbol = " "
format = "[$symbol$version]($style) "
display_private = false

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = " "

[python]
symbol = " "
format = "via [$symbol$version]($style) "
detect_files = ["requirements.txt", "pyproject.toml", "Pipfile", ".python-version"]

[rlang]
symbol = " "

[ruby]
symbol = " "
format = "via [$symbol$version]($style) "
detect_files = ["Gemfile", ".ruby-version"]

[rust]
symbol = " "

[scala]
symbol = " "

[shell]
disabled = false
format = "[$indicator]($style) "

[sudo]
disabled = false
format = "[as $symbol]($style)"

[swift]
symbol = " "

[status]
disabled = false
format = "[$symbol$status]($style) "

[username]
disabled = false
show_always = false
format = "[$user]($style)@"

[zig]
symbol = " "

[gradle]
symbol = " "

# Custom character styling
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"

# Command duration for long-running commands
[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "

# Direnv (like P10k's direnv segment)
[direnv]
format = "[direnv $loaded/$allowed]($style) "
disabled = false
